language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r ./requirements/requirements-test.txt --use-mirrors --quiet
script:
  - cd src && python manage.py test --settings={{ project_name }}.settings_test

